# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d1c96f0838b2a0ea1c2619e6dccecb586397f414ddc9d4b0a573ee99c228b691a022e35dc04cabcb2a1d652c34f8fe721f6e6fc23f4c981ff3bcaa9c119f82

test:
  secret_key_base: bf6c2e32093ff53897d092343803b546523374f47fb3ee7569b3a969ca0632ecac421e074fd0787f91c303dab9a1087ad6f535d2ae96d20f1d57fba2a9d6b9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
